const ESC_API="/api/escalation";
const ESC_FALLBACK_KEY="koteretPlus.escalation.lastGood.v142";
const ESC_SIGNAL_META={
  news:{icon:"📰",label:"מודיעין חדשותי",source:"כותרת פלוס",href:"/"},
  official:{icon:"🚨",label:"פיקוד העורף + רשמי",source:"OREF + צה״ל + Gov.il",href:"https://www.oref.org.il/"},
  aviation:{icon:"✈️",label:"תעופה אזרחית מעל איראן",source:"ADSB.lol",href:"https://www.adsb.lol/"},
  military:{icon:"🛰️",label:"נוכחות צבאית גלויה",source:"ADSB.lol",href:"https://www.adsb.lol/"},
  notam:{icon:"🛫",label:"NOTAM ומרחב אווירי",source:"רשות שדות התעופה",href:"https://ext.iaa.gov.il/aeroinfo/AeroInfo.aspx?msgType=Notam"},
  airrisk:{icon:"⚠️",label:"אזהרות תעופה אזוריות",source:"EASA Conflict Zones",href:"https://www.easa.europa.eu/en/domains/air-operations/czibs"},
  oil:{icon:"🛢️",label:"Brent",source:"Yahoo Finance / FRED",href:"https://fred.stlouisfed.org/series/DCOILBRENTEU"},
  us:{icon:"🇺🇸",label:"עמדת ארה״ב",source:"CENTCOM + DoD + State + White House",href:"https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/"},
  maritime:{icon:"⚓",label:"הורמוז והמפרץ",source:"UKMTO + U.S. MARAD",href:"https://www.ukmto.org/recent-incidents"},
  nuclear:{icon:"☢️",label:"איראן והגרעין",source:"IAEA",href:"https://www-news.iaea.org/EventList.aspx"},
  market:{icon:"📈",label:"שוק חיזוי",source:"Polymarket",href:"https://polymarket.com/"},
  diplomatic:{icon:"🌍",label:"אזהרות בינלאומיות",source:"UK FCDO",href:"https://www.gov.uk/foreign-travel-advice/israel"}
};
const $=s=>document.querySelector(s);
const els={score:$("#escScore"),level:$("#escLevel"),updated:$("#escUpdated"),confidence:$("#escConfidence"),trend:$("#escTrend"),trendBox:$("#escTrendBox"),sources:$("#escSourcesActive"),coverage:$("#escCoverage"),elevated:$("#escElevated"),gauge:$("#escGauge"),gaugeCircle:$("#escGaugeCircle"),signals:$("#escSignals"),changes:$("#escChanges"),weights:$("#escWeights"),chart:$("#escChart"),chartLine:$("#escChartLine"),chartArea:$("#escChartArea"),chartEmpty:$("#escChartEmpty"),pizzaLevel:$("#pizzaLevel"),pizzaScore:$("#pizzaScore"),pizzaReason:$("#pizzaReason"),share:$("#shareEscalation"),toast:$("#escToast"),next:$("#escNextRefresh")};
let countdown=60,lastPayload=null,displayedScore=0;
function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,Number(n)||0))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function timeAgo(iso){const t=Date.parse(iso||"");if(!Number.isFinite(t))return "זמן לא ידוע";const s=Math.max(0,Math.round((Date.now()-t)/1000));if(s<45)return "עודכן עכשיו";if(s<3600)return `עודכן לפני ${Math.round(s/60)} דק׳`;if(s<86400)return `עודכן לפני ${Math.round(s/3600)} שעות`;return `עודכן לפני ${Math.round(s/86400)} ימים`}
function levelKey(score){if(score<30)return"routine";if(score<50)return"elevated";if(score<70)return"high";if(score<85)return"significant";return"exceptional"}
function showToast(text){if(!els.toast)return;els.toast.textContent=text;els.toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove("show"),1800)}
function animateScore(target){target=Math.round(clamp(target));const start=Number.isFinite(displayedScore)?displayedScore:target;if(window.matchMedia?.("(prefers-reduced-motion: reduce)").matches){displayedScore=target;els.score.textContent=target;return}const t0=performance.now(),dur=700;function frame(now){const p=Math.min(1,(now-t0)/dur),ease=1-Math.pow(1-p,3),v=Math.round(start+(target-start)*ease);els.score.textContent=v;if(p<1)requestAnimationFrame(frame);else displayedScore=target}requestAnimationFrame(frame)}
function renderSignals(signals=[]){const sorted=[...signals].sort((a,b)=>(b.weight||0)-(a.weight||0));els.signals.innerHTML=sorted.map(s=>{const m=ESC_SIGNAL_META[s.key]||{icon:"•",label:s.label||s.key,source:s.source||"מקור",href:s.sourceUrl||"#"};const available=s.available!==false;const stale=s.stale?" · שמור":"";return `<article class="esc-signal ${available?"":"unavailable"}"><div class="esc-signal-head"><span class="esc-signal-icon">${m.icon}</span><div class="esc-signal-score">${available?`<strong>${Math.round(clamp(s.score))}</strong><span>/100</span>`:`<strong>לא זמין</strong>`}</div></div><h3>${esc(s.label||m.label)}</h3><div class="esc-signal-meta">משקל ${Number(s.weight||0)}% · ${esc(s.freshness||"")}${stale}</div><p>${esc(s.reason||"אין פירוט זמין כרגע")}</p><div class="esc-signal-foot"><span>${available?(s.stale?"נתון אחרון שמור":"פעיל"):"הוסר זמנית מהחישוב"}</span><a href="${esc(s.sourceUrl||m.href)}" ${String(s.sourceUrl||m.href).startsWith("/")?"":"target=\"_blank\" rel=\"noopener noreferrer\""}>${esc(s.source||m.source)} ↗</a></div></article>`}).join("")||'<div class="esc-loading-card">אין עדיין נתוני סיגנלים.</div>'}
function renderChanges(changes=[]){els.changes.innerHTML=(changes.length?changes:["המערכת עדיין אוספת מספיק נתונים כדי להסביר את השינוי."]).slice(0,6).map(x=>`<li>${esc(x)}</li>`).join("")}
function renderWeights(signals=[]){els.weights.innerHTML=signals.map(s=>`<span class="esc-weight">${esc(s.label||s.key)} <b>${Number(s.weight||0)}%</b></span>`).join("")}
function renderChart(history=[]){const rows=history.filter(x=>Number.isFinite(Number(x?.score))&&Number.isFinite(Date.parse(x?.at))).slice(-900);if(rows.length<2){els.chartLine.setAttribute("d","");els.chartArea.setAttribute("d","");els.chartEmpty.style.display="grid";return}els.chartEmpty.style.display="none";const minT=Date.now()-72*3600000,maxT=Date.now(),W=900,H=240,padY=15;const usable=rows.filter(r=>Date.parse(r.at)>=minT);const data=usable.length>1?usable:rows;const pts=data.map(r=>{const t=Date.parse(r.at),x=clamp((t-minT)/(maxT-minT),0,1)*W,y=H-padY-(clamp(r.score)/100)*(H-padY*2);return[x,y]});const d=pts.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" ");els.chartLine.setAttribute("d",d);els.chartArea.setAttribute("d",`${d} L${pts[pts.length-1][0].toFixed(1)},${H} L${pts[0][0].toFixed(1)},${H} Z`)}
function renderPizza(pizza){if(!pizza||pizza.available===false){els.pizzaLevel.textContent="לא זמין";els.pizzaScore.textContent="סיגנל ניסיוני";els.pizzaReason.textContent=pizza?.reason||"PizzINT אינו זמין כרגע. הסיגנל אינו משפיע על המדד.";return}els.pizzaLevel.textContent=pizza.level||"DOUGHCON —";els.pizzaScore.textContent=Number.isFinite(Number(pizza.score))?`ציון ניסיוני ${Math.round(pizza.score)}/100`:"0% משקל";els.pizzaReason.textContent=pizza.reason||"מוצג לצורכי OSINT בלבד ואינו משפיע על המדד הראשי."}
function render(payload){if(!payload?.latest)return;lastPayload=payload;const x=payload.latest,score=Math.round(clamp(x.score));document.body.dataset.level=levelKey(score);animateScore(score);els.level.textContent=x.level||"—";els.gauge.style.setProperty("--score",score);if(els.gaugeCircle)els.gaugeCircle.style.strokeDashoffset=String(515.22-(515.22*score/100));els.updated.textContent=timeAgo(x.updatedAt);els.confidence.textContent=`ביטחון בחישוב: ${x.confidenceLabel||"—"}`;const delta=Number(x.delta6h||0),arrow=delta>1?"↑":delta<-1?"↓":"→";els.trend.textContent=`${arrow} ${Math.abs(delta).toFixed(0)} נק׳`;els.trendBox.dataset.trend=delta>1?"up":delta<-1?"down":"flat";els.sources.textContent=`${x.availableSignals||0} מתוך ${x.totalSignals||12}`;els.coverage.textContent=`${Math.round(x.coverage||0)}%`;els.elevated.textContent=String(x.elevatedSignals||0);renderSignals(x.signals||[]);renderChanges(x.changes||[]);renderWeights(x.signals||[]);renderChart(payload.history||[]);renderPizza(x.experimental?.pizza||payload.experimental?.pizza);try{localStorage.setItem(ESC_FALLBACK_KEY,JSON.stringify(payload))}catch{}}
async function load(){countdown=60;try{const r=await fetch(ESC_API,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();render(data)}catch(error){console.warn("Escalation refresh failed",error);if(!lastPayload){try{const cached=JSON.parse(localStorage.getItem(ESC_FALLBACK_KEY)||"null");if(cached)render(cached)}catch{}}}}
async function share(){const url=new URL("/escalation",location.origin).toString();const score=lastPayload?.latest?.score,title=`מדד ההסלמה של כותרת פלוס${Number.isFinite(Number(score))?` — ${Math.round(score)}/100`:""}`;try{if(navigator.share){await navigator.share({title,text:"רמת המתיחות האזורית בזמן אמת — כותרת פלוס",url});return}await navigator.clipboard.writeText(url);showToast("הקישור הועתק") }catch(error){if(error?.name!=="AbortError")showToast("אפשר להעתיק את הקישור משורת הכתובת")}}
els.share?.addEventListener("click",share);load();setInterval(()=>{if(!document.hidden)load()},60000);setInterval(()=>{countdown=Math.max(0,countdown-1);if(els.next)els.next.textContent=`${countdown} שנ׳`},1000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)load()});
