const ESC_API="/api/escalation";
const HOT_STORY_API="/api/hot-story";
const OFFICIAL_SITE_URL="https://koteretplus.com/";
const OFFICIAL_ESCALATION_URL="https://koteretplus.com/escalation";
const HOT_STORY_LOCAL_KEY="hadashota.publicLead.v1";
const ESC_FALLBACK_KEY="koteretPlus.escalation.lastGood.v146";
const ESC_SIGNAL_META={
  news:{icon:"📰",label:"מודיעין חדשותי",source:"כותרת פלוס",href:OFFICIAL_SITE_URL},
  official:{icon:"🚨",label:"פיקוד העורף + רשמי",source:"OREF + צה״ל + Gov.il",href:"https://www.oref.org.il/"},
  aviation:{icon:"✈️",label:"תעופה אזרחית מעל איראן",source:"ADSB.lol",href:"https://www.adsb.lol/"},
  military:{icon:"🛰️",label:"נוכחות צבאית גלויה",source:"ADSB.lol",href:"https://www.adsb.lol/"},
  notam:{icon:"🛫",label:"NOTAM ישראל ומרחב אווירי",source:"רשות שדות התעופה",href:"https://ext.iaa.gov.il/aeroinfo/AeroInfo.aspx?msgType=Notam"},
  airrisk:{icon:"⚠️",label:"אזהרות תעופה אזוריות",source:"EASA Conflict Zones",href:"https://www.easa.europa.eu/en/domains/air-operations/czibs"},
  oil:{icon:"🛢️",label:"Brent",source:"Yahoo Finance / FRED",href:"https://fred.stlouisfed.org/series/DCOILBRENTEU"},
  us:{icon:"🇺🇸",label:"עמדת ארה״ב",source:"CENTCOM + DoD + State + White House",href:"https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/"},
  maritime:{icon:"⚓",label:"הורמוז והמפרץ",source:"UKMTO/JMIC + U.S. MARAD",href:"https://www.ukmto.org/recent-incidents"},
  nuclear:{icon:"☢️",label:"איראן והגרעין",source:"IAEA",href:"https://www-news.iaea.org/EventList.aspx"},
  market:{icon:"📈",label:"שוק חיזוי",source:"Polymarket",href:"https://polymarket.com/"},
  diplomatic:{icon:"🌍",label:"אזהרות בינלאומיות",source:"UK FCDO + U.S. State",href:"https://www.gov.uk/foreign-travel-advice/israel"}
};
const $=s=>document.querySelector(s);
const els={score:$("#escScore"),level:$("#escLevel"),updated:$("#escUpdated"),confidence:$("#escConfidence"),trend:$("#escTrend"),trendBox:$("#escTrendBox"),sources:$("#escSourcesActive"),coverage:$("#escCoverage"),elevated:$("#escElevated"),gauge:$("#escGauge"),gaugeCircle:$("#escGaugeCircle"),signals:$("#escSignals"),changes:$("#escChanges"),weights:$("#escWeights"),chart:$("#escChart"),chartLine:$("#escChartLine"),chartArea:$("#escChartArea"),chartEmpty:$("#escChartEmpty"),pizzaLevel:$("#pizzaLevel"),pizzaScore:$("#pizzaScore"),pizzaReason:$("#pizzaReason"),share:$("#shareEscalation"),contactBtn:$("#escContactBtn"),contactModal:$("#escContactModal"),contactBackdrop:$("#escContactBackdrop"),contactClose:$("#escContactClose"),contactForm:$("#escContactForm"),contactName:$("#escContactName"),contactPhone:$("#escContactPhone"),contactEmail:$("#escContactEmail"),contactTopic:$("#escContactTopic"),contactMessage:$("#escContactMessage"),contactSubmit:$("#escContactSubmit"),contactStatus:$("#escContactStatus"),toast:$("#escToast"),next:$("#escNextRefresh"),hotTitle:$("#escHotStoryTitle"),hotSources:$("#escHotStorySources"),hotAge:$("#escHotStoryAge"),hotLink:$("#escHotStoryLink"),hotMedia:$("#escHotStoryMedia"),hotImage:$("#escHotStoryImage"),toTop:$("#escToTop"),supportBtn:$("#escSupportBtn"),supportModal:$("#escSupportModal"),supportBackdrop:$("#escSupportBackdrop"),supportClose:$("#escSupportClose"),visitCount:$("#escVisitCount"),pushOffer:$("#escPushOffer"),pushBackdrop:$("#escPushBackdrop"),pushAccept:$("#escPushAccept"),pushLater:$("#escPushLater"),pushClose:$("#escPushClose"),pushText:$("#escPushText")};
let countdown=60,lastPayload=null,displayedScore=0;
function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,Number(n)||0))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function timeAgo(iso){const t=Date.parse(iso||"");if(!Number.isFinite(t))return "זמן לא ידוע";const s=Math.max(0,Math.round((Date.now()-t)/1000));if(s<45)return "עודכן עכשיו";if(s<3600)return `עודכן לפני ${Math.round(s/60)} דק׳`;if(s<86400)return `עודכן לפני ${Math.round(s/3600)} שעות`;return `עודכן לפני ${Math.round(s/86400)} ימים`}
function levelKey(score){if(score<30)return"routine";if(score<50)return"elevated";if(score<70)return"high";if(score<85)return"significant";return"exceptional"}
function showToast(text){if(!els.toast)return;els.toast.textContent=text;els.toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove("show"),1800)}
function animateScore(target){target=Math.round(clamp(target));const start=Number.isFinite(displayedScore)?displayedScore:target;if(window.matchMedia?.("(prefers-reduced-motion: reduce)").matches){displayedScore=target;els.score.textContent=target;return}const t0=performance.now(),dur=700;function frame(now){const p=Math.min(1,(now-t0)/dur),ease=1-Math.pow(1-p,3),v=Math.round(start+(target-start)*ease);els.score.textContent=v;if(p<1)requestAnimationFrame(frame);else displayedScore=target}requestAnimationFrame(frame)}
function renderSignals(signals=[]){const sorted=[...signals].sort((a,b)=>(b.weight||0)-(a.weight||0));els.signals.innerHTML=sorted.map(s=>{const m=ESC_SIGNAL_META[s.key]||{icon:"•",label:s.label||s.key,source:s.source||"מקור",href:s.sourceUrl||"#"};const available=s.available!==false;const stale=s.stale?` · שמור${Number.isFinite(Number(s.staleAgeMinutes))?` ${Math.max(1,Math.round(Number(s.staleAgeMinutes)))} דק׳`:""}`:"";return `<article class="esc-signal ${available?"":"unavailable"}"><div class="esc-signal-head"><span class="esc-signal-icon">${m.icon}</span><div class="esc-signal-score">${available?`<strong>${Math.round(clamp(s.score))}</strong><span>/100</span>`:`<strong>לא זמין</strong>`}</div></div><h3>${esc(s.label||m.label)}</h3><div class="esc-signal-meta">משקל ${Number(s.weight||0)}% · ${esc(s.freshness||"")}${stale}</div><p>${esc(s.reason||"אין פירוט זמין כרגע")}</p><div class="esc-signal-foot"><span>${available?(s.stale?"נתון שמור במשקל דועך":"פעיל"):"הוסר זמנית מהחישוב"}</span><a href="${esc(s.sourceUrl||m.href)}" ${String(s.sourceUrl||m.href).startsWith("/")?"":"target=\"_blank\" rel=\"noopener noreferrer\""}>${esc(s.source||m.source)} ↗</a></div></article>`}).join("")||'<div class="esc-loading-card">אין עדיין נתוני סיגנלים.</div>'}
function renderChanges(changes=[]){els.changes.innerHTML=(changes.length?changes:["המערכת עדיין אוספת מספיק נתונים כדי להסביר את השינוי."]).slice(0,6).map(x=>`<li>${esc(x)}</li>`).join("")}
function renderWeights(signals=[]){els.weights.innerHTML=signals.map(s=>`<span class="esc-weight">${esc(s.label||s.key)} <b>${Number(s.weight||0)}%</b></span>`).join("")}
function renderChart(history=[]){const rows=history.filter(x=>Number.isFinite(Number(x?.score))&&Number.isFinite(Date.parse(x?.at))).slice(-900);if(rows.length<2){els.chartLine.setAttribute("d","");els.chartArea.setAttribute("d","");els.chartEmpty.style.display="grid";return}els.chartEmpty.style.display="none";const minT=Date.now()-72*3600000,maxT=Date.now(),W=900,H=240,padY=15;const usable=rows.filter(r=>Date.parse(r.at)>=minT);const data=usable.length>1?usable:rows;const pts=data.map(r=>{const t=Date.parse(r.at),x=clamp((t-minT)/(maxT-minT),0,1)*W,y=H-padY-(clamp(r.score)/100)*(H-padY*2);return[x,y]});const d=pts.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" ");els.chartLine.setAttribute("d",d);els.chartArea.setAttribute("d",`${d} L${pts[pts.length-1][0].toFixed(1)},${H} L${pts[0][0].toFixed(1)},${H} Z`)}
function renderPizza(pizza){if(!pizza||pizza.available===false){els.pizzaLevel.textContent="לא זמין";els.pizzaScore.textContent="סיגנל ניסיוני";els.pizzaReason.textContent=pizza?.reason||"PizzINT אינו זמין כרגע. הסיגנל אינו משפיע על המדד.";return}els.pizzaLevel.textContent=pizza.level||"DOUGHCON —";els.pizzaScore.textContent=Number.isFinite(Number(pizza.score))?`ציון ניסיוני ${Math.round(pizza.score)}/100`:"0% משקל";els.pizzaReason.textContent=pizza.reason||"מוצג לצורכי OSINT בלבד ואינו משפיע על המדד הראשי."}
function normalizeHotStory(raw,source="server"){if(!raw)return null;const title=String(raw.title||raw?.entry?.title||raw?.entry?.item?.title||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();const sources=Math.max(0,Number(raw.sources??raw?.entry?.uniqueSources??0)||0);const at=raw.at||raw.latestAt||raw?.entry?.latestAt||raw?.entry?.item?.latestReportAt||raw?.entry?.item?.publishedAt||null;const fingerprint=String(raw.fingerprint||raw?.entry?.fingerprint||"");const savedAt=Number(raw.savedAt||0);const syncedAt=raw.syncedAt||raw.receivedAt||(savedAt?new Date(savedAt).toISOString():null);let link="",image="";try{const u=new URL(String(raw.link||""),OFFICIAL_SITE_URL);if(/^https?:$/.test(u.protocol))link=u.toString()}catch{}try{const u=new URL(String(raw.image||""),OFFICIAL_SITE_URL);if(/^https?:$/.test(u.protocol))image=u.toString()}catch{}if(!title)return null;return{title,sources,at,fingerprint,savedAt,syncedAt,source,link,image}}
function localHotStory(){try{const row=normalizeHotStory(JSON.parse(localStorage.getItem(HOT_STORY_LOCAL_KEY)||"null"),"local");if(!row)return null;const age=Date.now()-Number(row.savedAt||Date.parse(row.at||0)||0);return age<=3*60*1000?row:null}catch{return null}}
function renderHotStory(story){if(!story||!els.hotTitle)return;els.hotTitle.textContent=story.title;const n=Math.max(0,Number(story.sources)||0);els.hotSources.textContent=n?`${n} ${n===1?"מקור מדווח על ידיעה זו":"מקורות מדווחים על ידיעה זו"}`:"הכותרת החמה בכותרת פלוס";const freshness=story.at||story.syncedAt||(story.savedAt?new Date(story.savedAt).toISOString():null);els.hotAge.textContent=freshness?timeAgo(freshness):"מתעדכן אוטומטית";if(els.hotLink){els.hotLink.href=story.link||OFFICIAL_SITE_URL;els.hotLink.target="_blank";els.hotLink.rel="noopener noreferrer";}if(els.hotMedia&&els.hotImage){if(story.image){els.hotImage.src=story.image;els.hotImage.alt=story.title;els.hotMedia.hidden=false;els.hotImage.onerror=()=>{els.hotImage.removeAttribute("src");els.hotMedia.hidden=true}}else{els.hotImage.removeAttribute("src");els.hotMedia.hidden=true}}}
async function loadHotStory(){const local=localHotStory();if(local)renderHotStory(local);try{const r=await fetch(HOT_STORY_API,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const server=normalizeHotStory(await r.json(),"server");if(!server)return;const freshestLocal=localHotStory();if(freshestLocal&&freshestLocal.fingerprint&&server.fingerprint&&freshestLocal.fingerprint===server.fingerprint){renderHotStory({...server,title:freshestLocal.title,sources:freshestLocal.sources||server.sources,source:"local+server"});return}renderHotStory(server)}catch(error){if(!local)console.warn("Hot story refresh failed",error)}}
function render(payload){if(!payload?.latest)return;lastPayload=payload;const x=payload.latest,score=Math.round(clamp(x.score));document.body.dataset.level=levelKey(score);animateScore(score);els.level.textContent=x.level||"—";els.gauge.style.setProperty("--score",score);if(els.gaugeCircle)els.gaugeCircle.style.strokeDashoffset=String(515.22-(515.22*score/100));els.updated.textContent=timeAgo(x.updatedAt);els.confidence.textContent=`ביטחון בחישוב: ${x.confidenceLabel||"—"}`;const delta=Number(x.delta6h||0),arrow=delta>1?"↑":delta<-1?"↓":"→";els.trend.textContent=`${arrow} ${Math.abs(delta).toFixed(0)} נק׳`;els.trendBox.dataset.trend=delta>1?"up":delta<-1?"down":"flat";els.sources.textContent=`${x.availableSignals||0} מתוך ${x.totalSignals||12}`;els.coverage.textContent=`${Math.round(x.coverage||0)}%`;els.elevated.textContent=String(x.elevatedSignals||0);renderSignals(x.signals||[]);renderChanges(x.changes||[]);renderWeights(x.signals||[]);renderChart(payload.history||[]);renderPizza(x.experimental?.pizza||payload.experimental?.pizza);try{localStorage.setItem(ESC_FALLBACK_KEY,JSON.stringify(payload))}catch{}}
async function load(){countdown=60;try{const presence=`presenceDeviceId=${encodeURIComponent(escalationAnalyticsDeviceId())}`;const r=await fetch(`${ESC_API}${ESC_API.includes("?")?"&":"?"}${presence}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();render(data)}catch(error){console.warn("Escalation refresh failed",error);if(!lastPayload){try{const cached=JSON.parse(localStorage.getItem(ESC_FALLBACK_KEY)||"null");if(cached)render(cached)}catch{}}}}
function escalationAnalyticsDeviceId(){let id=localStorage.getItem("hadashota.pushDeviceId");if(id)return id;try{id=crypto.randomUUID()}catch{id=`kp-${Date.now()}-${Math.random().toString(36).slice(2)}`}localStorage.setItem("hadashota.pushDeviceId",id);return id}
async function trackEscalationVisit(){try{const r=await fetch("/api/analytics/visit",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",keepalive:true,body:JSON.stringify({page:"escalation",deviceId:escalationAnalyticsDeviceId(),userAgent:navigator.userAgent.slice(0,220),referrer:document.referrer||""})});const d=await r.json().catch(()=>null);if(d?.pageTotal!=null&&els.visitCount)els.visitCount.textContent=new Intl.NumberFormat("he-IL").format(Number(d.pageTotal)||0)}catch{try{const r=await fetch("/api/analytics/public?page=escalation",{cache:"no-store"});const d=await r.json();if(d?.pageTotal!=null&&els.visitCount)els.visitCount.textContent=new Intl.NumberFormat("he-IL").format(Number(d.pageTotal)||0)}catch{}}}
function escalationIsIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1)}
function escalationStandalone(){return window.matchMedia?.("(display-mode: standalone)")?.matches||navigator.standalone===true}async function escalationReadyServiceWorker(){const first=await navigator.serviceWorker.register("/sw.js?v=180.0.0",{updateViaCache:"none"});return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("Service Worker עדיין לא מוכן — נסו שוב בעוד רגע")),8000);navigator.serviceWorker.ready.then(reg=>{clearTimeout(timer);resolve(reg||first)},error=>{clearTimeout(timer);reject(error)})})}
function escB64Key(value){const padding="=".repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function escalationEnsurePush(){
  if(escalationIsIOS()&&!escalationStandalone())throw new Error("באייפון: לחצו שיתוף → הוסף למסך הבית, פתחו משם ואז הפעילו התראות");
  if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw new Error("הדפדפן אינו תומך ב-Push");
  let permission=Notification.permission;if(permission==="default")permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("לא ניתנה הרשאה להתראות");
  if(!localStorage.getItem("hadashota.pushPreferencesInitialized")){localStorage.setItem("hadashota.pushNews","1");localStorage.setItem("hadashota.pushEscalation","1");localStorage.setItem("hadashota.pushPreferencesInitialized","1")}
  if(localStorage.getItem("hadashota.alertDesktop")===null){localStorage.setItem("hadashota.alertDesktop","1");localStorage.setItem("hadashota.alertDesktopInitialized","1")}
  const reg=await escalationReadyServiceWorker();const cfg=await fetch("/api/push/config",{cache:"no-store"}).then(r=>r.json());if(!cfg?.publicKey)throw new Error("מערכת ה-Push אינה זמינה כרגע");
  let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:escB64Key(cfg.publicKey)});
  const deviceId=escalationAnalyticsDeviceId();
  const alertCities=(()=>{try{return JSON.parse(localStorage.getItem("hadashota.alertCities")||"[]")}catch{return[]}})();
  const r=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription:sub.toJSON(),deviceId,userAgent:navigator.userAgent.slice(0,220),preferences:{news:localStorage.getItem("hadashota.pushNews")!=="0",escalation:localStorage.getItem("hadashota.pushEscalation")!=="0",alerts:localStorage.getItem("hadashota.alertDesktop")==="1",alertAllIsrael:localStorage.getItem("hadashota.alertAllIsrael")!=="0",alertCities:Array.isArray(alertCities)?alertCities.slice(0,30):[]}})});if(!r.ok)throw new Error("לא הצלחנו להשלים את ההרשמה");
  try{reg.active?.postMessage({type:"SET_PUSH_DEVICE_ID",deviceId});navigator.serviceWorker.controller?.postMessage({type:"SET_PUSH_DEVICE_ID",deviceId})}catch{}
  localStorage.setItem("hadashota.headlineNotifications","1");localStorage.setItem("hadashota.notificationPromptChoice","accepted");localStorage.removeItem("hadashota.notificationSnoozeUntil");return true
}
function setEscPushOfferVisible(visible){if(els.pushOffer)els.pushOffer.hidden=!visible;if(els.pushBackdrop)els.pushBackdrop.hidden=!visible}
async function maybeShowEscPushOffer(){if(!els.pushOffer||!("serviceWorker" in navigator))return;const snooze=Number(localStorage.getItem("hadashota.notificationSnoozeUntil")||0);if(snooze>Date.now())return;const lastPromptAt=Number(localStorage.getItem("hadashota.notificationPromptLastShownAt")||0);if(lastPromptAt&&Date.now()-lastPromptAt<30*60*1000)return;const iosNeedsInstall=escalationIsIOS()&&!escalationStandalone();if(iosNeedsInstall){if(els.pushText)els.pushText.textContent="באייפון: כדי לקבל Push גם כשהאתר סגור, לחצו שיתוף ↥ → הוסף למסך הבית, פתחו את כותרת פלוס מהאייקון ואז הפעילו התראות.";if(els.pushAccept)els.pushAccept.textContent="איך מפעילים באייפון";localStorage.setItem("hadashota.notificationPromptLastShownAt",String(Date.now()));setEscPushOfferVisible(true);return}if(!("Notification" in window)||!("PushManager" in window))return;if(Notification.permission==="denied")return;if(localStorage.getItem("hadashota.headlineNotifications")==="1"&&Notification.permission==="granted"){escalationEnsurePush().catch(()=>{});return}if(els.pushAccept)els.pushAccept.textContent="הפעלת התראות";localStorage.setItem("hadashota.notificationPromptLastShownAt",String(Date.now()));setEscPushOfferVisible(true)}
function snoozeEscPush(){localStorage.setItem("hadashota.notificationPromptChoice","later");localStorage.setItem("hadashota.notificationSnoozeUntil",String(Date.now()+24*60*60*1000));setEscPushOfferVisible(false)}
els.pushAccept?.addEventListener("click",async()=>{if(escalationIsIOS()&&!escalationStandalone()){if(els.pushAccept.dataset.stage==="ios-help"){setEscPushOfferVisible(false);return}if(els.pushText)els.pushText.textContent="1. לחצו שיתוף ↥ בדפדפן. 2. בחרו ‘הוסף למסך הבית’. 3. פתחו את כותרת פלוס מהאייקון שנוסף. 4. כשהחלון יופיע שוב, לחצו ‘הפעלת התראות’ ואשרו את חלון iOS.";els.pushAccept.dataset.stage="ios-help";els.pushAccept.textContent="הבנתי";return}els.pushAccept.disabled=true;els.pushAccept.textContent="ממתין לאישור…";if(els.pushText)els.pushText.innerHTML="הדפדפן יציג עכשיו בקשת הרשאה. בחרו <strong>אפשר / Allow</strong>; חלון האבטחה הזה שייך לדפדפן ולא ניתן לעקוף אותו.";try{await escalationEnsurePush();els.pushOffer?.classList.add("is-success");if(els.pushText)els.pushText.textContent="ההתראות הופעלו ✓ חדשות חמות ודופק ההסלמה משתמשים באותו אישור Push. אפשר לסנן סוגים בהגדרות באתר המלא.";els.pushAccept.textContent="הופעל ✓";setTimeout(()=>{setEscPushOfferVisible(false)},1700)}catch(error){const denied=("Notification" in window)&&Notification.permission==="denied";if(els.pushText)els.pushText.innerHTML=denied?"הדפדפן חסם התראות. לחצו על <strong>סמל המנעול / הגדרות האתר</strong> ליד הכתובת → <strong>התראות</strong> → <strong>אפשר</strong>, ואז נסו שוב.":String(error?.message||error);els.pushAccept.disabled=false;els.pushAccept.textContent="נסו שוב"}});els.pushLater?.addEventListener("click",snoozeEscPush);els.pushClose?.addEventListener("click",()=>{setEscPushOfferVisible(false)});els.pushBackdrop?.addEventListener("click",snoozeEscPush);
let escSupportScrollLockY=null;function lockEscSupportPage(){if(escSupportScrollLockY!==null)return;const y=Math.max(0,window.scrollY||window.pageYOffset||0);escSupportScrollLockY=y;document.body.style.position="fixed";document.body.style.top=`-${y}px`;document.body.style.left="0";document.body.style.right="0";document.body.style.width="100%"}function unlockEscSupportPage(){if(escSupportScrollLockY===null)return;const y=escSupportScrollLockY;escSupportScrollLockY=null;document.body.style.position="";document.body.style.top="";document.body.style.left="";document.body.style.right="";document.body.style.width="";requestAnimationFrame(()=>window.scrollTo({top:y,left:0,behavior:"auto"}))}
function openEscSupport(){if(!els.supportModal)return;lockEscSupportPage();els.supportModal.hidden=false;els.supportModal.setAttribute("aria-hidden","false");document.documentElement.classList.add("esc-modal-open");document.body.classList.add("esc-modal-open");setEscPushOfferVisible(false);requestAnimationFrame(()=>els.supportClose?.focus())}
function closeEscSupport(){if(!els.supportModal)return;els.supportModal.hidden=true;els.supportModal.setAttribute("aria-hidden","true");unlockEscSupportPage();if(els.contactModal?.hidden!==false){document.documentElement.classList.remove("esc-modal-open");document.body.classList.remove("esc-modal-open")}els.supportBtn?.focus()}
function openEscContact(){if(!els.contactModal)return;setEscContactStatus("");els.contactModal.hidden=false;els.contactModal.setAttribute("aria-hidden","false");document.documentElement.classList.add("esc-modal-open");document.body.classList.add("esc-modal-open");setEscPushOfferVisible(false);requestAnimationFrame(()=>els.contactName?.focus())}
function closeEscContact(){if(!els.contactModal)return;els.contactModal.hidden=true;els.contactModal.setAttribute("aria-hidden","true");document.documentElement.classList.remove("esc-modal-open");document.body.classList.remove("esc-modal-open")}
function setEscContactStatus(text,state=""){if(!els.contactStatus)return;els.contactStatus.textContent=text||"";if(state)els.contactStatus.dataset.state=state;else delete els.contactStatus.dataset.state}async function submitEscContact(event){event.preventDefault();const form=els.contactForm;if(!form)return;setEscContactStatus("");if(!form.checkValidity()){form.reportValidity();setEscContactStatus("נא להשלים את כל שדות החובה ולוודא שכתובת האימייל תקינה.","error");return}const name=String(els.contactName?.value||"").trim(),phone=String(els.contactPhone?.value||"").trim(),email=String(els.contactEmail?.value||"").trim(),topic=String(els.contactTopic?.value||"דופק ההסלמה"),message=String(els.contactMessage?.value||"").trim();const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(email);if(name.length<2||phone.replace(/\D/g,"").length<5||!emailOk||message.length<2){setEscContactStatus("נא לבדוק שם, טלפון, אימייל והודעה ולנסות שוב.","error");return}if(els.contactSubmit){els.contactSubmit.disabled=true;els.contactSubmit.textContent="שולח…"}try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({name,phone,email,topic,message,source:"escalation"})});const data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(data?.error||"השליחה נכשלה");form.reset();setEscContactStatus("הפנייה התקבלה בהצלחה, נחזור אליך בהקדם.","success");showToast("הפנייה התקבלה בהצלחה");setTimeout(closeEscContact,2800)}catch(error){setEscContactStatus(String(error?.message||"השליחה נכשלה. נסו שוב בעוד רגע."),"error")}finally{if(els.contactSubmit){els.contactSubmit.disabled=false;els.contactSubmit.textContent="שליחת הודעה"}}}
async function share(){const url=OFFICIAL_ESCALATION_URL;const title="דופק ההסלמה – כמה אנחנו קרובים למלחמה? | כותרת פלוס";const text="📡 דופק ההסלמה – כמה אנחנו קרובים למלחמה? בדיקה אונליין בכותרת פלוס. היכנסו לראות את תמונת המצב העדכנית.";const clipboardText=`${text}\n${url}`;try{if(navigator.share){await navigator.share({title,text,url});return}await navigator.clipboard.writeText(clipboardText);showToast("טקסט השיתוף והקישור הועתקו")}catch(error){if(error?.name==="AbortError")return;try{const box=document.createElement("textarea");box.value=clipboardText;box.setAttribute("readonly","");box.style.position="fixed";box.style.opacity="0";document.body.appendChild(box);box.select();document.execCommand("copy");box.remove();showToast("טקסט השיתוף והקישור הועתקו")}catch{showToast("אפשר להעתיק את הקישור משורת הכתובת")}}}
let escHotStoryAnchor=null;
function syncEscalationMobileOrder(){
  const hot=document.querySelector(".esc-hot-story-wrap"),grid=document.querySelector(".esc-hero-grid");if(!hot||!grid)return;
  if(!escHotStoryAnchor){escHotStoryAnchor=document.createComment("esc-hot-story-home");hot.parentNode?.insertBefore(escHotStoryAnchor,hot);}
  if(window.matchMedia("(max-width:700px)").matches){if(hot.parentNode!==grid)grid.appendChild(hot);hot.classList.add("esc-hot-story-mobile");}
  else{hot.classList.remove("esc-hot-story-mobile");if(escHotStoryAnchor?.parentNode&&hot.parentNode!==escHotStoryAnchor.parentNode)escHotStoryAnchor.parentNode.insertBefore(hot,escHotStoryAnchor.nextSibling);}
}
window.addEventListener("resize",()=>{clearTimeout(syncEscalationMobileOrder.t);syncEscalationMobileOrder.t=setTimeout(syncEscalationMobileOrder,120)});

function updateToTop(){if(!els.toTop)return;const visible=window.scrollY>280;els.toTop.classList.toggle("is-visible",visible);els.toTop.setAttribute("aria-hidden",visible?"false":"true");els.toTop.tabIndex=visible?0:-1}
let toTopRaf=0;window.addEventListener("scroll",()=>{if(toTopRaf)return;toTopRaf=requestAnimationFrame(()=>{toTopRaf=0;updateToTop()})},{passive:true});
els.toTop?.addEventListener("click",()=>window.scrollTo({top:0,behavior:window.matchMedia?.("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));
els.share?.addEventListener("click",share);els.supportBtn?.addEventListener("click",openEscSupport);els.supportClose?.addEventListener("click",closeEscSupport);els.supportBackdrop?.addEventListener("click",closeEscSupport);els.contactBtn?.addEventListener("click",openEscContact);els.contactClose?.addEventListener("click",closeEscContact);els.contactBackdrop?.addEventListener("click",closeEscContact);els.contactForm?.addEventListener("submit",submitEscContact);document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!els.supportModal?.hidden){closeEscSupport();return}if(!els.contactModal?.hidden)closeEscContact()});syncEscalationMobileOrder();updateToTop();trackEscalationVisit();load();loadHotStory();setTimeout(maybeShowEscPushOffer,5000);setInterval(()=>{if(!document.hidden)load()},60000);setInterval(()=>{if(!document.hidden)loadHotStory()},15000);setInterval(()=>{countdown=Math.max(0,countdown-1);if(els.next)els.next.textContent=`${countdown} שנ׳`},1000);window.addEventListener("storage",event=>{if(event.key===HOT_STORY_LOCAL_KEY&&event.newValue){try{renderHotStory(normalizeHotStory(JSON.parse(event.newValue),"local"))}catch{}}});document.addEventListener("visibilitychange",()=>{if(!document.hidden){load();loadHotStory()}});
